name: elections_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
    # Clean Architecture Goodies
    equatable: ^2.0.5
    dartz: ^0.10.1
    get_it: ^7.2.0
    # Code Generations
    build_runner: ^2.3.3
    freezed: ^2.3.2
    freezed_annotation: ^2.2.0
    json_annotation: ^4.7.0
    json_serializable: ^6.5.4
    #  # Database
    firebase_core: ^2.4.0
    # UI/Ux
    flutter_launcher_icons: ^0.11.0
    flutter_native_splash: ^2.2.16
    device_preview: ^1.1.0
    google_fonts: ^3.0.1
    nil: ^1.1.1
    firebase_messaging: ^14.1.4
    flutter_local_notifications: ^13.0.0
    cloud_firestore: ^4.2.0
    firebase_auth: ^4.2.1
    expandable: ^5.0.1
    http: ^0.13.5
    flutter_svg: ^1.1.6
    dropdown_textfield: ^1.0.7
    firebase_dynamic_links: ^5.0.11
    intl: ^0.17.0
    timeago: ^3.3.0

  hexcolor: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/static/
    - assets/svgs/

