// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL_uubqyLyPqLsfpFxda4FqxufmHMlAgs',
    appId: '1:467928280528:android:d99c13506c80088ce51dd5',
    messagingSenderId: '467928280528',
    projectId: 'music-request-300',
    storageBucket: 'music-request-300.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvfE3qQvIIhuGaW4UEisBMz-qbvZQEEDo',
    appId: '1:467928280528:ios:cbfc1be95cc91876e51dd5',
    messagingSenderId: '467928280528',
    projectId: 'music-request-300',
    storageBucket: 'music-request-300.appspot.com',
    androidClientId: '467928280528-g2t5a29pcnqcon74upnuen2dp1abgc87.apps.googleusercontent.com',
    iosClientId: '467928280528-hp32ugo0agv5h3268bssb6abqe939ade.apps.googleusercontent.com',
    iosBundleId: 'com.musicrequestdj.app.musicRequesDj',
  );
}
