name: music_reques_dj
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # Clean Architecture Dependencies
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.5.0
  # Path Manipulations
  path: ^1.8.2
  path_provider: ^2.0.15
  # Code Generations
  build_runner: ^2.3.3
  freezed: ^2.3.3
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  json_serializable: ^6.6.2
  # Caching
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  # Database
  firebase_core: ^2.11.0
  firebase_auth: ^4.2.1
  firebase_messaging: ^14.5.0
  firebase_dynamic_links: ^5.2.0
  firebase_storage: ^11.2.2
  firebase_crashlytics: ^3.2.0
  firebase_performance: ^0.9.1+2
  firebase_analytics: ^10.4.1
  cloud_firestore: ^4.6.0
  # UI/UX
  flutter_local_notifications: ^14.0.0+1
  flutter_native_splash: ^2.2.19
  google_fonts: ^4.0.4
  google_sign_in: ^6.1.0
  device_preview: ^1.1.0
  flutter_svg: ^2.0.5
  intl: ^0.18.0
  http: ^0.13.6
  timeago: ^3.3.0
  ionicons: ^0.2.2
  share_plus: ^7.0.1
  local_auth: ^2.1.6
  intl_phone_field: ^3.1.0
  image_picker: ^0.8.7+5
  url_launcher: ^6.1.11
  flutter_launcher_icons: ^0.13.1
  shimmer: ^3.0.0
  cached_network_image: ^3.2.3
  webview_flutter: ^3.0.4
  search_page: ^2.3.0
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  vibration: ^1.8.1
  flutter_slidable: ^3.0.0
  pdf: ^3.10.4
  open_file: ^3.3.2
  dio: ^5.3.0
# dart run flutter_native_splash:create
flutter_native_splash:
  image: assets/static/logo.png
  color: "#ffffff"
  image_dark: "assets/static/logo.png"

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  image_path: "assets/static/logo.png"
  adaptive_icon_background: "assets/static/logo.png"
  adaptive_icon_foreground: "assets/static/logo.png"
  remove_alpha_ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/static/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
